namespace SMSLiteModels.Entities.Dtos;

public sealed record SurveyGridRow(
    int? SurveyId,
    DateTime? SurveyDate,
    int? SampleId,
    int? PeriodId,
    short? ActiveFlag,
    DateTime? StartDate,
    DateTime? StopDate,
    int? SampleMonth,
    short? HqReviewFlag,
    int? PopulatedRows,
    short? MailFlag,
    short? CawiFlag,
    short? CatiFlag,
    short? CapiFlag,
    DateTime? MailStartDate,
    DateTime? MailStopDate,
    DateTime? CawiStartDate,
    DateTime? CawiStopDate,
    DateTime? CapiStartDate,
    DateTime? CapiStopDate,
    DateTime? CatiStartDate,
    DateTime? CatiStopDate,
    string? CatiApp,
    string? SurveyTitle,
    string? SurveySubtitle,
    int? FrequencyCode,
    string? FrequencyDescription,
    string? ProjectCode,
    string? OmbNumber,
    DateTime? OmbExpires,
    string? BaseMonth,
    string? MarkedVersion,
    string? SampleName,
    string? ElmoSurveyId,
    string? ElmoPeriodId,
    string? ElmoMonth,
    int? TotalRowCount);

public sealed record SurveyInstancePageRequest(
    int RowLimit = 20,
    int RowOffset = 0,
    int? SurveyId = null,
    int? SampleId = null,
    string? SurveySearch = null,
    DateTime? SurveyDate = null,
    DateTime? StartDate = null,
    DateTime? StopDate = null,
    bool Mail = false,
    bool Cawi = false,
    bool Cati = false,
    bool Capi = false,
    bool HqReview = false);

public sealed record SurveyInstancePageResponse(
    IReadOnlyList<SurveyGridRow> Rows,
    int TotalRowCount);

public sealed record SurveyInstanceDetailResponse(
    int? SampleId,
    string? SampleName,
    int? SurveyId,
    string? Title,
    string? SubTitle,
    string? SurveyFrequency,
    string? Version,
    DateTime? SurveyDate,
    DateTime ReferenceDate,
    DateTime? SurveyStartDate,
    DateTime? SurveyStopDate,
    bool HqReview,
    string? ProjectCode,
    string? OmbNumber,
    DateTime? OmbExpiration,
    string? ElmoSurveyId,
    string? ElmoPeriodId,
    string? ElmoMonth,
    string? MarkedVersion,
    string? BaseMonth,
    DateTime? MailStartDate,
    DateTime? MailStopDate,
    DateTime? CawiStartDate,
    DateTime? CawiStopDate,
    DateTime? CapiStartDate,
    DateTime? CapiStopDate,
    DateTime? CatiStartDate,
    DateTime? CatiStopDate,
    int TotalSample,
    int TotalReceived,
    int TotalDeleted,
    int CompleteCount,
    int RefusalCount,
    int InaccessibleCount,
    int OtherCompleteCount,
    int OfficeHoldCount,
    int ActiveNotCheckedInCount,
    int MailReceivedCount,
    int CawiReceivedCount,
    int CapiReceivedCount,
    int ReadiReceivedCount,
    int OtherModeReceivedCount);
