namespace sms_lite.Models;

public sealed record SurveyInstance(
    int? SurveyId,
    DateTime? SurveyDate,
    int? SampleId,
    int? PeriodId,
    short? ActiveFlag,
    DateTime? StartDate,
    DateTime? StopDate,
    int? SampleMonth,
    short? HqReviewFlag,
    int? PopulatedRows,
    short? MailFlag,
    short? CawiFlag,
    short? CatiFlag,
    short? CapiFlag,
    DateTime? MailStartDate,
    DateTime? MailStopDate,
    DateTime? CawiStartDate,
    DateTime? CawiStopDate,
    DateTime? CapiStartDate,
    DateTime? CapiStopDate,
    DateTime? CatiStartDate,
    DateTime? CatiStopDate,
    string? CatiApp,
    string? SurveyTitle,
    string? SurveySubtitle,
    int? FrequencyCode,
    string? FrequencyDescription,
    string? ProjectCode,
    string? OmbNumber,
    DateTime? OmbExpires,
    string? BaseMonth,
    string? MarkedVersion,
    string? SampleName,
    string? ElmoSurveyId,
    string? ElmoPeriodId,
    string? ElmoMonth,
    int? TotalRowCount);

public sealed record SurveyInstanceQuery(
    int RowLimit,
    int RowOffset,
    int? SurveyId = null,
    int? SampleId = null,
    string? SurveySearch = null,
    DateTime? SurveyDate = null,
    DateTime? StartDate = null,
    DateTime? StopDate = null,
    bool Mail = false,
    bool Cawi = false,
    bool Cati = false,
    bool Capi = false,
    bool HqReview = false);

public sealed record SurveyInstanceCheckin(
    DateTime? ResponseDate,
    int? ResponseCode,
    int? DataCaptureCode,
    int? DcmsCodeId);
